{
 "title": "AOSS logs ",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "All aoss executions",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"aoss\"} |= ``"
    }
   ]
  },
  {
   "title": "success commands",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"aoss\", server_tag=\"server-test-2\"} |= `apt`"
    }
   ]
  },
  {
   "title": "server 1 logs which succeed ",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"aoss\", server_id=\"f6fb4529-b7e6-43b6-8b49-0e9f4c00e416\", status=\"Success\"} |= ``"
    }
   ]
  },
  {
   "title": "Failed commands red(server 1 ) and green server 2",
   "type": "logs",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"aoss\", status=\"Failed\"} |= ``"
    }
   ]
  }
 ]
}