version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki_data:/loki
      - ./loki_config.yaml:/etc/loki/local-config.yaml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    volumes:
      - ./promtail.yml:/etc/promtail/config.yml
      - ./logs:/var/log/aoss
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.4.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana_data:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - prometheus
      - loki

volumes:
  prometheus_data:
  loki_data:
  grafana_data:


# services:
#   prometheus:
#     image: prom/prometheus:v2.54.1
#     container_name: prometheus
#     ports:
#       - "9090:9090"
#     volumes:
#       - /mnt/d/BE_project/Aoss_project/ops/prometheus.yml:/etc/prometheus/prometheus.yml
#       - prometheus_data:/prometheus
#     command:
#       - "--config.file=/etc/prometheus/prometheus.yml"
#       - "--storage.tsdb.path=/prometheus"
#       - "--web.enable-lifecycle"

#   loki:
#     image: grafana/loki:2.9.4
#     container_name: loki
#     ports:
#       - "3100:3100"
#     command: -config.file=/etc/loki/local-config.yaml
#     volumes:
#       -volumes:
#       - /mnt/d/BE_project/Aoss_project/ops/loki_data:/loki
#       - /mnt/d/BE_project/Aoss_project/ops/loki_config.yaml:/etc/loki/local-config.yaml

#   promtail:
#     image: grafana/promtail:2.9.4
#     container_name: promtail
#     volumes:
#       - /mnt/d/BE_project/Aoss_project/ops/promtail.yml:/etc/promtail/config.yml
#       - /mnt/d/BE_project/Aoss_project/ops/logs:/var/log/aoss
#     command: -config.file=/etc/promtail/config.yml

#   grafana:
#     image: grafana/grafana:10.4.3
#     container_name: grafana
#     ports:
#       - "3000:3000"
#     environment:
#       - GF_SECURITY_ADMIN_USER=admin
#       - GF_SECURITY_ADMIN_PASSWORD=admin
#     volumes:
#       - /mnt/d/BE_project/Aoss_project/ops/grafana_data:/var/lib/grafana


# volumes:
#   prometheus_data:
#   loki_data:
#   grafana_data: